CREATE TYPE "EventCategory" AS ENUM ('EVENTO', 'PISCINA_LIBRE', 'ACADEMIA');

ALTER TABLE "events"
ADD COLUMN "category" "EventCategory" NOT NULL DEFAULT 'EVENTO',
ADD COLUMN "advanceAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
