/**
 * Configura los horarios exclusivos de sábado de Academia VMT (septiembre 2026)
 * para que sus cuatro clases vayan del 12/09/2026 al 03/10/2026, dentro de la
 * vigencia solicitada hasta el 05/10/2026.
 *
 * Corrige dos capas:
 * - futuros: fechas válidas y cantidad de clases del TicketType;
 * - existentes: selección guardada en la orden y entitlements del carnet.
 *
 * Dry-run:
 *   node --env-file=.env.production .\node_modules\tsx\dist\cli.mjs --tsconfig tsconfig.json scripts\configure-vmt-saturday-start.ts
 * Aplicar:
 *   node --env-file=.env.production .\node_modules\tsx\dist\cli.mjs --tsconfig tsconfig.json scripts\configure-vmt-saturday-start.ts --apply
 */

import { Prisma } from "@prisma/client"
import { prisma } from "@/lib/prisma"
import { normalizeScheduleSelections } from "@/lib/ticket-schedule"

const EVENT_ID = "cmsqihgwf04sy01p8tjw289a9"
const EXPECTED_TITLE = "ACADEMIA DE NATACIÓN (VMT/FDNDA) - DEL 1 AL 30 DE SEPTIEMBRE"
const EXPECTED_SUCURSAL = "04"
const TARGET_DATES = ["2026-09-12", "2026-09-19", "2026-09-26", "2026-10-03"] as const
const PREVIOUS_TARGET_DATES = ["2026-09-12", "2026-09-19", "2026-09-26"]
const ACCESS_END = "2026-10-05"
const TARGET_SCHEDULE_CODES = ["000080", "000032", "000033", "000034", "000035", "000036", "000037", "000038"] as const
const OLD_AUTOGENERATED_DATES = ["2026-08-20", "2026-08-21", "2026-08-22", "2026-08-23"]

const APPLY = process.argv.includes("--apply")

function dateKey(value: Date): string {
    return value.toISOString().slice(0, 10)
}

function sameValues(left: readonly string[], right: readonly string[]): boolean {
    return left.length === right.length && left.every((value, index) => value === right[index])
}

function attendeeDataWithTargetDates(value: Prisma.JsonValue | null): Prisma.InputJsonValue {
    if (!Array.isArray(value)) throw new Error("attendeeData no es un arreglo")

    return value.map((entry) => {
        if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
            throw new Error("attendeeData contiene un asistente inválido")
        }

        const attendee = entry as Record<string, Prisma.JsonValue>
        const currentDates = normalizeScheduleSelections(attendee.scheduleSelections).map((selection) => selection.date)
        const isAllowedCurrentState =
            currentDates.length === 0 ||
            sameValues(currentDates, OLD_AUTOGENERATED_DATES) ||
            sameValues(currentDates, PREVIOUS_TARGET_DATES) ||
            sameValues(currentDates, TARGET_DATES)
        if (!isAllowedCurrentState) {
            throw new Error(
                `El asistente ${String(attendee.name ?? attendee.dni ?? "-")} tiene fechas manuales inesperadas: ${currentDates.join(", ")}`,
            )
        }

        return {
            ...attendee,
            scheduleSelections: TARGET_DATES.map((date) => ({ date })),
        }
    }) as Prisma.InputJsonValue
}

async function loadState() {
    return prisma.event.findUnique({
        where: { id: EVENT_ID },
        select: {
            id: true,
            title: true,
            category: true,
            servilexSucursalCode: true,
            startDate: true,
            endDate: true,
            ticketTypes: {
                where: { servilexScheduleCode: { in: [...TARGET_SCHEDULE_CODES] } },
                orderBy: { sortOrder: "asc" },
                select: {
                    id: true,
                    name: true,
                    isPackage: true,
                    packageDaysCount: true,
                    validDays: true,
                    capacityByDate: true,
                    servilexServiceCode: true,
                    servilexScheduleCode: true,
                    tickets: {
                        where: { status: { not: "CANCELLED" } },
                        select: {
                            id: true,
                            status: true,
                            entitlements: {
                                orderBy: { date: "asc" },
                                select: { id: true, date: true, status: true },
                            },
                            scans: { where: { result: "VALID" }, select: { id: true } },
                        },
                    },
                    orderItems: {
                        where: { order: { status: { not: "CANCELLED" } } },
                        select: { id: true, attendeeData: true, order: { select: { status: true } } },
                    },
                },
            },
        },
    })
}

async function main() {
    const event = await loadState()
    if (!event) throw new Error(`No existe el evento ${EVENT_ID}`)
    if (event.title !== EXPECTED_TITLE) throw new Error(`Título inesperado: ${event.title}`)
    if (event.category !== "ACADEMIA") throw new Error(`Categoría inesperada: ${event.category}`)
    if (event.servilexSucursalCode !== EXPECTED_SUCURSAL) {
        throw new Error(`Sede inesperada: ${event.servilexSucursalCode}`)
    }
    if (dateKey(event.startDate) > TARGET_DATES[0] || TARGET_DATES.at(-1)! > ACCESS_END) {
        throw new Error(`La vigencia objetivo es inválida: ${TARGET_DATES[0]} → ${ACCESS_END}`)
    }

    const foundCodes = new Set(event.ticketTypes.map((ticketType) => ticketType.servilexScheduleCode))
    const missingCodes = TARGET_SCHEDULE_CODES.filter((code) => !foundCodes.has(code))
    if (missingCodes.length > 0 || event.ticketTypes.length !== TARGET_SCHEDULE_CODES.length) {
        throw new Error(`No se encontraron exactamente los 8 horarios sabatinos. Faltan: ${missingCodes.join(", ") || "-"}`)
    }

    let ticketCount = 0
    let orderItemCount = 0
    let entitlementCount = 0
    const preparedOrderItems = new Map<string, Prisma.InputJsonValue>()

    for (const ticketType of event.ticketTypes) {
        if (!ticketType.name.trim().toUpperCase().startsWith("SÁB (")) {
            throw new Error(`El horario ${ticketType.servilexScheduleCode} ya no es exclusivo de sábado: ${ticketType.name}`)
        }
        if (ticketType.servilexServiceCode !== "I68") {
            throw new Error(`Servicio inesperado en ${ticketType.name}: ${ticketType.servilexServiceCode}`)
        }
        if (!ticketType.isPackage || ![3, 4].includes(ticketType.packageDaysCount ?? -1)) {
            throw new Error(`Paquete inesperado en ${ticketType.name}: ${ticketType.packageDaysCount}`)
        }
        if (ticketType.capacityByDate) {
            throw new Error(`${ticketType.name} usa cupo por fecha; requiere migrar también sus inventarios`)
        }

        const configuredDates = Array.isArray(ticketType.validDays)
            ? ticketType.validDays.filter((value): value is string => typeof value === "string").sort()
            : []
        if (
            configuredDates.length > 0 &&
            !sameValues(configuredDates, PREVIOUS_TARGET_DATES) &&
            !sameValues(configuredDates, TARGET_DATES)
        ) {
            throw new Error(`${ticketType.name} tiene fechas configuradas inesperadas: ${configuredDates.join(", ")}`)
        }

        for (const ticket of ticketType.tickets) {
            const currentDates = ticket.entitlements.map((entitlement) => dateKey(entitlement.date))
            const isAllowedCurrentState =
                currentDates.length === 0 ||
                sameValues(currentDates, OLD_AUTOGENERATED_DATES) ||
                sameValues(currentDates, PREVIOUS_TARGET_DATES) ||
                sameValues(currentDates, TARGET_DATES)
            if (!isAllowedCurrentState) {
                throw new Error(`El carnet ${ticket.id} tiene fechas inesperadas: ${currentDates.join(", ")}`)
            }
            if (ticket.scans.length > 0 || ticket.entitlements.some((entitlement) => entitlement.status !== "AVAILABLE")) {
                throw new Error(`El carnet ${ticket.id} ya tiene asistencias/entitlements usados; no se modificará automáticamente`)
            }
            ticketCount += 1
            entitlementCount += ticket.entitlements.length
        }

        for (const orderItem of ticketType.orderItems) {
            preparedOrderItems.set(orderItem.id, attendeeDataWithTargetDates(orderItem.attendeeData))
            orderItemCount += 1
        }
    }

    console.table(event.ticketTypes.map((ticketType) => ({
        codigo: ticketType.servilexScheduleCode,
        horario: ticketType.name,
        carnets: ticketType.tickets.length,
        items: ticketType.orderItems.length,
        clasesAntes: ticketType.packageDaysCount,
        fechasAntes: Array.isArray(ticketType.validDays) ? ticketType.validDays.join(", ") || "(vacío)" : "(vacío)",
        fechasDespues: TARGET_DATES.join(", "),
    })))
    console.log(`Plan: 8 horarios, ${ticketCount} carnets, ${orderItemCount} items y ${entitlementCount} entitlements existentes.`)

    if (!APPLY) {
        console.log("DRY RUN: no se modificó producción. Usa --apply para aplicar.")
        return
    }

    await prisma.$transaction(async (tx) => {
        for (const ticketType of event.ticketTypes) {
            await tx.ticketType.update({
                where: { id: ticketType.id },
                data: {
                    packageDaysCount: TARGET_DATES.length,
                    validDays: [...TARGET_DATES],
                },
            })

            for (const ticket of ticketType.tickets) {
                await tx.ticketDayEntitlement.deleteMany({ where: { ticketId: ticket.id } })
                await tx.ticketDayEntitlement.createMany({
                    data: TARGET_DATES.map((date) => ({
                        ticketId: ticket.id,
                        date: new Date(`${date}T12:00:00Z`),
                        status: "AVAILABLE" as const,
                    })),
                })
            }
        }

        for (const [id, attendeeData] of preparedOrderItems) {
            await tx.orderItem.update({ where: { id }, data: { attendeeData } })
        }
    })

    const verification = await loadState()
    if (!verification || verification.ticketTypes.length !== TARGET_SCHEDULE_CODES.length) {
        throw new Error("Falló la verificación posterior: horarios incompletos")
    }
    for (const ticketType of verification.ticketTypes) {
        const configuredDates = Array.isArray(ticketType.validDays)
            ? ticketType.validDays.filter((value): value is string => typeof value === "string").sort()
            : []
        if (ticketType.packageDaysCount !== TARGET_DATES.length || !sameValues(configuredDates, TARGET_DATES)) {
            throw new Error(`Falló la verificación del horario ${ticketType.servilexScheduleCode}`)
        }
        for (const ticket of ticketType.tickets) {
            const dates = ticket.entitlements.map((entitlement) => dateKey(entitlement.date))
            if (!sameValues(dates, TARGET_DATES)) throw new Error(`Falló la verificación del carnet ${ticket.id}`)
        }
        for (const orderItem of ticketType.orderItems) {
            const attendees = Array.isArray(orderItem.attendeeData) ? orderItem.attendeeData : []
            for (const attendee of attendees) {
                const record = attendee && typeof attendee === "object" && !Array.isArray(attendee)
                    ? attendee as Record<string, Prisma.JsonValue>
                    : {}
                const dates = normalizeScheduleSelections(record.scheduleSelections).map((selection) => selection.date)
                if (!sameValues(dates, TARGET_DATES)) throw new Error(`Falló la verificación del item ${orderItem.id}`)
            }
        }
    }

    console.log(`APLICADO Y VERIFICADO: horarios del 12/09/2026 al 05/10/2026 (clases hasta el 03/10).`)
}

main()
    .finally(() => prisma.$disconnect())
    .catch((error) => {
        console.error(error)
        process.exitCode = 1
    })
