/**
 * Corrige los calendarios de Academia VMT (septiembre 2026) según la frecuencia
 * real de cada tipo de entrada. Actualiza tanto ventas futuras como carnets ya
 * emitidos, sin tocar carnets con asistencias.
 *
 * Dry-run:
 *   node --env-file=.env.production .\node_modules\tsx\dist\cli.mjs --tsconfig tsconfig.json scripts\configure-vmt-september-frequency-starts.ts
 * Aplicar:
 *   node --env-file=.env.production .\node_modules\tsx\dist\cli.mjs --tsconfig tsconfig.json scripts\configure-vmt-september-frequency-starts.ts --apply
 */

import { Prisma } from "@prisma/client"
import { prisma } from "@/lib/prisma"
import { normalizeScheduleSelections, parseTicketScheduleConfig } from "@/lib/ticket-schedule"

const EVENT_ID = "cmsqihgwf04sy01p8tjw289a9"
const EXPECTED_TITLE = "ACADEMIA DE NATACIÓN (VMT/FDNDA) - DEL 1 AL 30 DE SEPTIEMBRE"
const EXPECTED_SUCURSAL = "04"
const EXPECTED_START = "2026-08-20"
const EXPECTED_END = "2026-09-30"

const LMV_DATES = [
    "2026-09-02", "2026-09-04", "2026-09-07", "2026-09-09",
    "2026-09-11", "2026-09-14", "2026-09-16", "2026-09-18",
    "2026-09-21", "2026-09-23", "2026-09-25", "2026-09-28",
] as const
const MJS_DATES = [
    "2026-09-01", "2026-09-03", "2026-09-05", "2026-09-08",
    "2026-09-10", "2026-09-12", "2026-09-15", "2026-09-17",
    "2026-09-19", "2026-09-22", "2026-09-24", "2026-09-26",
] as const
const MJ_DATES = [
    "2026-09-01", "2026-09-03", "2026-09-08", "2026-09-10",
    "2026-09-15", "2026-09-17", "2026-09-22", "2026-09-24",
] as const
const SATURDAY_DATES = ["2026-09-12", "2026-09-19", "2026-09-26", "2026-10-03"] as const

type FrequencyConfig = {
    label: string
    codes: readonly string[]
    targetDates: readonly string[]
    expectedName: RegExp
    allowedPreviousDates?: readonly (readonly string[])[]
}

const FREQUENCIES: readonly FrequencyConfig[] = [
    {
        label: "Lun - Mié - Vie",
        codes: ["000001", "000002", "000003", "000004", "000005", "000008", "000009", "000010", "000011", "000012", "000013", "000077", "000148"],
        targetDates: LMV_DATES,
        expectedName: /^LUN - MIE - VIE /,
    },
    {
        label: "Mar - Jue - Sáb",
        codes: ["000075", "000014", "000040", "000041", "000042", "000076"],
        targetDates: MJS_DATES,
        expectedName: /^MAR - JUE .*SÁB/,
    },
    {
        label: "Mar - Jue",
        codes: ["000079", "000025", "000026", "000027", "000028", "000031", "000021", "000022", "000023", "000024", "000081", "000078", "000149"],
        targetDates: MJ_DATES,
        expectedName: /^MAR - JUE \(/,
    },
    {
        label: "Sábado",
        codes: ["000080", "000032", "000033", "000034", "000035", "000036", "000037", "000038"],
        targetDates: SATURDAY_DATES,
        expectedName: /^SÁB \(/,
        allowedPreviousDates: [["2026-09-12", "2026-09-19", "2026-09-26"]],
    },
] as const

const APPLY = process.argv.includes("--apply")

function dateKey(value: Date): string {
    return value.toISOString().slice(0, 10)
}

function sameValues(left: readonly string[], right: readonly string[]): boolean {
    return left.length === right.length && left.every((value, index) => value === right[index])
}

function oldAutogeneratedDates(count: number): string[] {
    const dates: string[] = []
    const cursor = new Date("2026-08-20T12:00:00Z")
    for (let index = 0; index < count; index++) {
        dates.push(dateKey(cursor))
        cursor.setUTCDate(cursor.getUTCDate() + 1)
    }
    return dates
}

function isAllowedCalendar(currentDates: readonly string[], config: FrequencyConfig): boolean {
    const sorted = [...currentDates].sort()
    return (
        sorted.length === 0 ||
        sameValues(sorted, oldAutogeneratedDates(config.targetDates.length)) ||
        sameValues(sorted, config.targetDates) ||
        (config.allowedPreviousDates ?? []).some((dates) => sameValues(sorted, dates))
    )
}

function attendeeDataWithTargetDates(
    value: Prisma.JsonValue | null,
    config: FrequencyConfig,
): Prisma.InputJsonValue {
    if (!Array.isArray(value)) throw new Error("attendeeData no es un arreglo")

    return value.map((entry) => {
        if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
            throw new Error("attendeeData contiene un asistente inválido")
        }

        const attendee = entry as Record<string, Prisma.JsonValue>
        const currentDates = normalizeScheduleSelections(attendee.scheduleSelections)
            .map((selection) => selection.date)
            .sort()
        if (!isAllowedCalendar(currentDates, config)) {
            throw new Error(
                `El asistente ${String(attendee.name ?? attendee.dni ?? "-")} tiene fechas manuales inesperadas: ${currentDates.join(", ")}`,
            )
        }

        return {
            ...attendee,
            scheduleSelections: config.targetDates.map((date) => ({ date })),
        }
    }) as Prisma.InputJsonValue
}

async function loadState() {
    return prisma.event.findUnique({
        where: { id: EVENT_ID },
        select: {
            id: true,
            title: true,
            category: true,
            servilexSucursalCode: true,
            startDate: true,
            endDate: true,
            ticketTypes: {
                orderBy: { sortOrder: "asc" },
                select: {
                    id: true,
                    name: true,
                    isPackage: true,
                    packageDaysCount: true,
                    validDays: true,
                    capacityByDate: true,
                    servilexScheduleCode: true,
                    tickets: {
                        where: { status: { not: "CANCELLED" } },
                        select: {
                            id: true,
                            entitlements: {
                                orderBy: { date: "asc" },
                                select: { date: true, status: true },
                            },
                            scans: { where: { result: "VALID" }, select: { id: true } },
                        },
                    },
                    orderItems: {
                        where: { order: { status: { not: "CANCELLED" } } },
                        select: { id: true, attendeeData: true },
                    },
                },
            },
        },
    })
}

async function main() {
    const event = await loadState()
    if (!event) throw new Error(`No existe el evento ${EVENT_ID}`)
    if (event.title !== EXPECTED_TITLE) throw new Error(`Título inesperado: ${event.title}`)
    if (event.category !== "ACADEMIA") throw new Error(`Categoría inesperada: ${event.category}`)
    if (event.servilexSucursalCode !== EXPECTED_SUCURSAL) {
        throw new Error(`Sede inesperada: ${event.servilexSucursalCode}`)
    }
    if (dateKey(event.startDate) !== EXPECTED_START || dateKey(event.endDate) !== EXPECTED_END) {
        throw new Error(`Rango inesperado: ${dateKey(event.startDate)} → ${dateKey(event.endDate)}`)
    }

    const configByCode = new Map(
        FREQUENCIES.flatMap((config) => config.codes.map((code) => [code, config] as const))
    )
    const expectedCodes = new Set(configByCode.keys())
    const foundCodes = new Set(event.ticketTypes.map((ticketType) => ticketType.servilexScheduleCode ?? ""))
    const missingCodes = [...expectedCodes].filter((code) => !foundCodes.has(code))
    const unexpected = event.ticketTypes.filter(
        (ticketType) => !ticketType.servilexScheduleCode || !expectedCodes.has(ticketType.servilexScheduleCode)
    )
    if (missingCodes.length > 0 || unexpected.length > 0 || event.ticketTypes.length !== expectedCodes.size) {
        throw new Error(
            `Matriz de horarios inesperada. Faltan: ${missingCodes.join(", ") || "-"}; sobran: ${unexpected.map((ticketType) => ticketType.name).join(" | ") || "-"}`
        )
    }

    let ticketCount = 0
    let orderItemCount = 0
    let entitlementCount = 0
    let changedTicketTypes = 0
    let changedTickets = 0
    const preparedOrderItems = new Map<string, Prisma.InputJsonValue>()
    const plan: Array<Record<string, string | number>> = []

    for (const ticketType of event.ticketTypes) {
        const code = ticketType.servilexScheduleCode as string
        const config = configByCode.get(code)
        if (!config) throw new Error(`Sin configuración para ${code}`)
        if (!config.expectedName.test(ticketType.name.trim().toUpperCase())) {
            throw new Error(`El código ${code} no coincide con ${config.label}: ${ticketType.name}`)
        }
        if (!ticketType.isPackage || ticketType.packageDaysCount !== config.targetDates.length) {
            throw new Error(`Paquete inesperado en ${ticketType.name}: ${ticketType.packageDaysCount}`)
        }
        if (ticketType.capacityByDate) {
            throw new Error(`${ticketType.name} usa cupo por fecha; requiere migrar inventarios`)
        }

        const configuredDates = parseTicketScheduleConfig(ticketType.validDays).dates
        if (!isAllowedCalendar(configuredDates, config)) {
            throw new Error(`${ticketType.name} tiene fechas configuradas inesperadas: ${configuredDates.join(", ")}`)
        }
        if (!sameValues(configuredDates, config.targetDates)) changedTicketTypes += 1

        const beforeCalendars = new Set<string>()
        for (const ticket of ticketType.tickets) {
            const currentDates = ticket.entitlements.map((entitlement) => dateKey(entitlement.date)).sort()
            beforeCalendars.add(currentDates.join(", ") || "(vacío)")
            if (!isAllowedCalendar(currentDates, config)) {
                throw new Error(`El carnet ${ticket.id} tiene fechas inesperadas: ${currentDates.join(", ")}`)
            }
            if (ticket.scans.length > 0 || ticket.entitlements.some((entitlement) => entitlement.status !== "AVAILABLE")) {
                throw new Error(`El carnet ${ticket.id} ya tiene asistencias o accesos usados; se aborta toda la operación`)
            }
            if (!sameValues(currentDates, config.targetDates)) changedTickets += 1
            ticketCount += 1
            entitlementCount += ticket.entitlements.length
        }

        for (const orderItem of ticketType.orderItems) {
            preparedOrderItems.set(orderItem.id, attendeeDataWithTargetDates(orderItem.attendeeData, config))
            orderItemCount += 1
        }

        plan.push({
            codigo: code,
            frecuencia: config.label,
            horario: ticketType.name,
            carnets: ticketType.tickets.length,
            calendariosAntes: beforeCalendars.size,
            fechasTipoAntes: configuredDates.join(", ") || "(vacío)",
            fechasDespues: config.targetDates.join(", "),
        })
    }

    console.table(plan)
    console.log(
        `Plan: ${changedTicketTypes} tipos y ${changedTickets} de ${ticketCount} carnets requieren cambio; ` +
        `${orderItemCount} items y ${entitlementCount} entitlements fueron validados.`
    )

    if (!APPLY) {
        console.log("DRY RUN: no se modificó producción. Usa --apply para aplicar.")
        return
    }

    await prisma.$transaction(async (tx) => {
        for (const ticketType of event.ticketTypes) {
            const code = ticketType.servilexScheduleCode as string
            const config = configByCode.get(code)
            if (!config) throw new Error(`Sin configuración para ${code}`)

            await tx.ticketType.update({
                where: { id: ticketType.id },
                data: {
                    packageDaysCount: config.targetDates.length,
                    validDays: [...config.targetDates],
                },
            })

            for (const ticket of ticketType.tickets) {
                await tx.ticketDayEntitlement.deleteMany({ where: { ticketId: ticket.id } })
                await tx.ticketDayEntitlement.createMany({
                    data: config.targetDates.map((date) => ({
                        ticketId: ticket.id,
                        date: new Date(`${date}T12:00:00Z`),
                        status: "AVAILABLE" as const,
                    })),
                })
            }
        }

        for (const [id, attendeeData] of preparedOrderItems) {
            await tx.orderItem.update({ where: { id }, data: { attendeeData } })
        }
    })

    const verification = await loadState()
    if (!verification || verification.ticketTypes.length !== expectedCodes.size) {
        throw new Error("Falló la verificación posterior: horarios incompletos")
    }

    for (const ticketType of verification.ticketTypes) {
        const code = ticketType.servilexScheduleCode as string
        const config = configByCode.get(code)
        if (!config) throw new Error(`Sin configuración para ${code}`)
        const configuredDates = parseTicketScheduleConfig(ticketType.validDays).dates
        if (ticketType.packageDaysCount !== config.targetDates.length || !sameValues(configuredDates, config.targetDates)) {
            throw new Error(`Falló la verificación del horario ${code}`)
        }
        for (const ticket of ticketType.tickets) {
            const dates = ticket.entitlements.map((entitlement) => dateKey(entitlement.date))
            if (!sameValues(dates, config.targetDates)) throw new Error(`Falló la verificación del carnet ${ticket.id}`)
        }
        for (const orderItem of ticketType.orderItems) {
            const attendees = Array.isArray(orderItem.attendeeData) ? orderItem.attendeeData : []
            for (const attendee of attendees) {
                const record = attendee && typeof attendee === "object" && !Array.isArray(attendee)
                    ? attendee as Record<string, Prisma.JsonValue>
                    : {}
                const dates = normalizeScheduleSelections(record.scheduleSelections).map((selection) => selection.date)
                if (!sameValues(dates, config.targetDates)) throw new Error(`Falló la verificación del item ${orderItem.id}`)
            }
        }
    }

    console.log(
        `APLICADO Y VERIFICADO: ${expectedCodes.size} horarios, ${ticketCount} carnets y ${orderItemCount} items con calendario por frecuencia.`
    )
}

main()
    .finally(() => prisma.$disconnect())
    .catch((error) => {
        console.error(error)
        process.exitCode = 1
    })
